### ISSUE TITLE
Segmentation fault possibly in disc_SetTrack

### ISSUE THREAD

**Issue by sophom** [tari01/libodiosacd#1]
I can't seem to use odio or odio-sacd. First I used the Ubuntu PPA for all the code. After it crashed and I started debugging, I downloaded the source from github for both odio-sacd and libodiosacd and recreated the crash. Looking at the coredump I see this:

```
➜  TOMMY  ./odio-sacd/data/usr/bin/odio-sacd -i TOMMY_sacd_disk1.iso -o TOMMY_MC_Disk1


Odio SACD v20.5.12
--------------------
Command-line decoder

[1]    5015 segmentation fault (core dumped)  ./odio-sacd/data/usr/bin/odio-sacd -i TOMMY_sacd_disk1.iso -o TOMMY_MC_Disk1

➜  TOMMY  gdb ./odio-sacd/data/usr/bin/odio-sacd core                                 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./odio-sacd/data/usr/bin/odio-sacd...
[New LWP 5019]
[New LWP 5015]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./odio-sacd/data/usr/bin/odio-sacd -i TOMMY_sacd_disk1.iso -o TOMMY_MC_Disk1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa525315991 in disc_SetTrack (pDisc=0x55e2f32deb20, nTrack=nTrack@entry=0, nArea=nArea@entry=AREA_MULCH) at src/reader/disc.c:1060
1060	        if (strlen(pSacdArea->lAreaTrackTexts[nTrack].sTrackPerformer))
[Current thread is 1 (Thread 0x7fa524f97700 (LWP 5019))]
(gdb) bt
#0  0x00007fa525315991 in disc_SetTrack (pDisc=0x55e2f32deb20, nTrack=nTrack@entry=0, nArea=nArea@entry=AREA_MULCH) at src/reader/disc.c:1060
#1  0x00007fa5253182d6 in odiolibsacd_Init (pOdioLibSacd=pOdioLibSacd@entry=0x55e2f32de970, nSubsong=nSubsong@entry=0, nSampleRate=<optimized out>, nArea=nArea@entry=AREA_MULCH)
    at src/libodiosacd.c:347
#2  0x00007fa525318af7 in odiolibsacd_OnDecode (pData=0x55e2f32de970) at src/libodiosacd.c:627
#3  0x00007fa5250f1609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#4  0x00007fa525232293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```
I haven't dug much further in to this. The old sacd works fine with this iso. If you have suggestions on how to proceed with the debug let me know.

**Comment by tari01** [comment]
@sophom 

Thanks for reporting this. Does this happen every time in exactly the same way? If so, could you upload the ISO somewhere and send me the link so I could test it myself? (You can E-mail me to make it private)

**Comment by tari01** [comment]
I think we should be OK now. A new release is out.

**Comment by sophom** [comment]
Yep. Works. Thank you!
